### ISSUE TITLE
Cannot find module 'kinvey-nativescript-sdk/push'

### ISSUE THREAD

**Issue by tjvantoll** [Kinvey/nativescript-sdk#28]
Hey all,

A problem came up on the [NativeScript forum](https://discourse.nativescript.org/t/kinvey-push-notifications-using-kinvey-sdk/3132/) that I was able to verify. Seems like the push module that the [Kinvey push documentation](https://devcenter.kinvey.com/nativescript/guides/push#) says to use is not published with the plugin.

#### Steps to Reproduce

1. Start a new NativeScript app and install the Kinvey {N} SDK.
2. Add the following import to any file.

```
import { Push } from 'kinvey-nativescript-sdk/push';
```

#### Expected Result

No TypeScript errors.

#### Actual Result

The following TypeScript error.

``` TypeScript
Cannot find module 'kinvey-nativescript-sdk/push'.
```

#### Version of Kinvey NativeScript SDK

3.9.3

#### NodeJS version

6.11.4

**Comment by tejasranade** [comment]
@tjvantoll thanks for the bug report. I am seeing the problem as well. We'll have an update soon.

**Comment by thomasconner** [comment]
This has been fixed in https://github.com/Kinvey/js-sdk/pull/171 and will be available in the next release. I will update this issue when the new release is available.

**Comment by nikola6789** [comment]
Hi there, do we know when the new release with the fix will be published? Thanks.

**Comment by thomasconner** [comment]
@nikola6789 @tjvantoll This was fixed with the release of version 3.9.4.

**Comment by finger563** [comment]
I'm still seeing this in 3.11.1

**Comment by thomasconner** [comment]
Ok. We are fixing some other issues related to Push this sprint. We will take a look while we are fixing these issues. Expect a fix at the end of next week. I will update here when this fix is released.

**Comment by finger563** [comment]
Hi @thomasconner any update on this? :)

**Comment by thomasconner** [comment]
The Push module is available an can be accessed with 

```javascript
import { Push } from 'kinvey-nativescript-sdk/push';
```

but there is another issue that is causing push to not work and will need to be fixed. Right now I don't have a time estimate for that fix but it is something that is priority for us to fix.

**Comment by finger563** [comment]
I do have
```ts
import * as Kinvey from 'kinvey-nativescript-sdk';
import { Push } from 'kinvey-nativescript-sdk/push';
```
and I still get:
```
error TS2307: Cannot find module 'kinvey-nativescript-sdk/push'.
```
with version (from `package.json`): `"kinvey-nativescript-sdk": "^3.11.1"`

**Comment by nikym23** [comment]
+1

**Comment by bradmartin** [comment]
Hey @thomasconner with `3.11.1` isn't the `Push` class just exposed in the `kinvey-nativescript-sdk` itself and not via the sub directory? I looked into the module and the `push` files (android & ios) are just in the root of the module. So for now I'm trying `import * as Kinvey from ...` and using `Kinvey.Push...` to access the methods in the `Push`. I have not confirmed that this works yet, having some local build/device issues with my android device at the moment.

**Comment by thomasconner** [comment]
Hey @bradmartin. `3.11.1` should have the `Push` class exposed as a separate module accessed by `kinvey-nativescript-sdk/push` and not at `kinvey-nativescript-sdk`. It looks like there might be an issue where it is available but the TypeScript definitions file has not been updated which is causing the error `error TS2307: Cannot find module 'kinvey-nativescript-sdk/push'`. I will try and fix the TypeScript definition file to see if that resolves the issue. 

cc: @finger563 @nikym23

**Comment by bradmartin** [comment]
@thomasconner - yep you're right, was finally able to test that and while the typings pass, it's not valid like you mentioned 👍 
Wouldn't just putting the `push` files into a sub directory `/push` along with a typings file fix this issue?

At least that's what I'd do for now 😄

**Comment by bradmartin** [comment]
Also, I'm referring to the NS SDK having this done here https://github.com/Kinvey/nativescript-sdk and not the monorepo for all the kinvey-js projects 👍

**Comment by finger563** [comment]
Has any fix for this been pushed? specifically related to `.register` failing?

**Comment by thomasconner** [comment]
No there has not been a fix pushed at the moment. It is scheduled to be fixed in this sprint.

**Comment by thomasconner** [comment]
This has been fixed with [3.11.5](
https://github.com/Kinvey/nativescript-sdk/releases/tag/v3.11.5) release.
